'use client'

import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'

// Define styles for the PDF
const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#FFFDD0', // Cozy Cream
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
    borderBottom: '2px solid #FFD1DC', // Cozy Pink
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    color: '#5D5D5D',
    fontWeight: 'bold',
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: '#B2AC88', // Sage
  },
  daySection: {
    marginBottom: 15,
    padding: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
  },
  dayHeader: {
    fontSize: 14,
    color: '#FFD1DC', // Pink
    fontWeight: 'bold',
    marginBottom: 5,
  },
  activityRow: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  time: {
    width: 60,
    fontSize: 10,
    color: '#B2AC88',
    fontWeight: 'bold',
  },
  details: {
    flex: 1,
  },
  activityName: {
    fontSize: 10,
    color: '#5D5D5D',
    fontWeight: 'bold',
  },
  location: {
    fontSize: 9,
    color: '#9CA3AF',
    fontStyle: 'italic',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    color: '#B2AC88',
    fontSize: 8,
    borderTop: '1px solid #FFD1DC',
    paddingTop: 10,
  },
})

// Data Shape
type Activity = {
  id: string
  day_number: number
  start_time: string
  activity_name: string
  location: string
  notes: string
}

type ItineraryDocumentProps = {
  destination: string
  activities: Activity[]
}

export default function ItineraryDocument({ destination, activities }: ItineraryDocumentProps) {
  // Group by day
  const grouped = activities.reduce((acc, curr) => {
    const day = curr.day_number
    if (!acc[day]) acc[day] = []
    acc[day].push(curr)
    return acc
  }, {} as Record<number, Activity[]>)

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>Trip to {destination}</Text>
          <Text style={styles.subtitle}>Generated by Cozy Cloud • The Academic Hub</Text>
        </View>

        {/* Content */}
        {Object.keys(grouped).map((day) => (
          <View key={day} style={styles.daySection}>
            <Text style={styles.dayHeader}>Day {day}</Text>
            
            {grouped[parseInt(day)].map((act) => (
              <View key={act.id} style={styles.activityRow}>
                <Text style={styles.time}>{act.start_time}</Text>
                <View style={styles.details}>
                  <Text style={styles.activityName}>{act.activity_name}</Text>
                  {act.location && <Text style={styles.location}>{act.location}</Text>}
                </View>
              </View>
            ))}
          </View>
        ))}

        {/* Footer */}
        <Text style={styles.footer}>
          "The world is a book and those who do not travel read only one page." 🌍
        </Text>
      </Page>
    </Document>
  )
}